################################################################################
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################
version: '2.4'

# Define networks first
networks:
  unomi-net:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.3
    container_name: elasticsearch
    volumes:
      - unomi-3-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=contextElasticSearch
    networks:
      - unomi-3
    ports:
      - 9200:9200

  node-1:
    image: apache/unomi:${project.version}
    container_name: unomi
    environment:
      - UNOMI_AUTO_START=elasticsearch
      - UNOMI_ELASTICSEARCH_ADDRESSES=elasticsearch:9200
      # Debug settings
      - KARAF_DEBUG=${DEBUG:-false}
      - KARAF_DEBUG_PORT=${DEBUG_PORT:-5005}
      - KARAF_DEBUG_SUSPEND=${DEBUG_SUSPEND:-n}
    ports:
      - 8181:8181
      - 9443:9443
      - 8102:8102
      # Debug port
      - "${DEBUG_PORT:-5005}:5005"
    networks:
      - unomi-3
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      unomi-net:
        aliases:
          - unomi

volumes: unomi-3-elasticsearch-data:
    driver: local

networks:
  unomi-3:
    name: unomi-3
    ipam:
      config:
        - subnet: 172.24.32.0/24
