# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Unomi CI - Documentation and deployment

on:
  push:
    branches: [ master, unomi-1.x ]

jobs:
  docs-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: apache.snapshots.https
        server-username: NEXUS_USER
        server-password: NEXUS_PW

    - name: Generate documentation
      run: mvn -U -B -e clean install -DskipTests javadoc:aggregate source:aggregate

    - name: Deploying
      run: mvn deploy -DskipTests
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PW: ${{ secrets.NEXUS_PW }}
