# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish Javadoc and snapshots

on:
  push:
    branches: [ master, unomi-1.x ]

jobs:
  publish-docs-and-snapshots:
    name: Publish Javadoc and snapshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: apache.snapshots.https
          server-username: NEXUS_USER
          server-password: NEXUS_PW
      - name: Generate documentation
        run: mvn -U -ntp -e clean install -DskipTests javadoc:aggregate source:aggregate
      - name: Build & deploy snapshots
        run: mvn -ntp deploy -DskipTests
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}

  publish-docker-image:
    name: Push Docker image snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: apache.snapshots.https
          server-username: NEXUS_USER
          server-password: NEXUS_PW
      - name: Building & pushing Docker snapshot image
        run: mvn -ntp clean install -P docker; pushd docker; mvn -Ddocker.username=${{ secrets.DOCKERHUB_USER }} -Ddocker.password=${{ secrets.DOCKERHUB_TOKEN }} docker:push; popd
